services:
  backend:
    container_name: backend
    image: uaguape  # Your NestJS app image
    ports:
      - "3000:3000"
    depends_on:
      - postgres  # Ensure Postgres starts first
    build:
      context: .  # Set the build context to the backend app directory
      dockerfile: apps/backend/Dockerfile  # Specify the Dockerfile name (if different)
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000    

  postgres:
    image: postgres:15-alpine # Or a suitable Postgres image for ARM
    container_name: database
    restart: always
    ports:
      - "5432:5432" # Only needed if you want to access Postgres externally (not recommended)
    environment:
      POSTGRES_PASSWORD: glavotaner
      POSTGRES_DB: uaguape
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data across container restarts

volumes:
  postgres_data: