services:
  backend:
    container_name: backend
    image: uaguape
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000

  postgres:
    image: postgres:15-alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: glavotaner
      POSTGRES_DB: uaguape
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: