name: Deploy Backend to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Deploy to Raspberry Pi with Docker Compose
        uses: appleboy/ssh-action@v1.2.1
        with:
          # ... your SSH secrets and configuration ...
          script: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
              cd uaguape &&
              git pull origin main &&
              docker compose down &&
              docker compose up -d --build
            "
