name: Deploy Backend to Raspberry Pi


on:
  push:
    branches: [ main ]

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2


      - name: Deploy to Raspberry Pi with Docker Compose
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          debug: true
          timeout: 60
          script: |
              cd uaguape &&
              git pull origin main &&
              docker compose down &&
              docker compose up -d --build
            
