name: Deploy Backend to Raspberry Pi


on:
  push:
    branches: [ develop ]

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      
      - name: Deploy to Raspberry Pi with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          debug: true
          script: |
              echo "I'm in"
            
